[package]
name = "lang"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "0x6b73746b"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
